Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  #Configuring puppet provision
  config.vm.provision "puppet" do |puppet|
  puppet.environment_path = "C:/Priti/Masters/Practical Workspace/PA2577-BDCloud-PritiV/Basic Vagrant_Puppet provisioning/environments"
   puppet.environment = "test"
  end
  end
  